### ISSUE TITLE
HLS tutorial (R markdown) issue with data from different UTM zones

### ISSUE THREAD

**Issue by pjhurska** [nasa/HLS-Data-Resources#17]
@amfriesz When running the HLS tutorial with own polygon data (just one polygon geometry), which happens to situate on the border of two UTM zones, the solution on rows 502-509 to extract the CRS from the first asset in the `search_df` list does not work, as the list contains images from two different UTM zones, i.e from two different CRS.

Therefore, the code to "create a list of raster layers for each of our bands of interest (i.e., Red, NIR, and Fmask)" on rows 521-560 runs to a certain point, until it encounters data from that other zone, then failing with this error message: 
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'mask': [crop] extents do not overlap
```

**Comment by amfriesz** [comment]
@pjhurska, thanks for pointing that out. Would you be able to provide the polygon data/file you're working with?

**Comment by pjhurska** [comment]
Dear Aaron,

First of all, many thanks for the great tutorial, it helped me who is a complete beginner to STAC, to learn a new skill. Actually, I took your tutorial and modified it so 1) it now uses rstac instead of httr, which makes fetching all search results much easier (instead of just the first page), 2) detects in which Finnish utm zone the ROI polygon is and takes that as the reference extent into which all extracted satellite data is cropped, masked and reprojected. It not the most elegant solution and could be improved a lot, but It works for now as a demonstration. I am able to query and extract HLS data from the entire time series and filter out months which are out of growing season. I might put the R-markdown workflow to our github at some point.

Attached is the shapefile I used.

I have one question: in your code, fmask is fetched for every image scene, but I am not so sure if it is used anywhere in the process flow? How are unclear sky observations handled, is it done already in HLS processing or should the user utilize the fmask quality band to do additional filtering? I have noticed that the Sentinel-2 scenes often have cloud/shadow/snow artifacts while Landsat HLS scenes are much better quality.

Best regards

Pekka Hurskainen
Erikoistutkija / Senior Research Scientist
Suomen ympäristökeskus / Finnish Environment Institute (Syke)
Tiedontuotannon laatu / Quality of Information
+358 295 252 036
Latokartanonkaari 11
00790 Helsinki
www.syke.fi<http://www.syke.fi/> | www.environment.fi<https://www.environment.fi/en-US>

**Comment by pjhurska** [comment]
Actually I ended up writing own solution, following your excellent tutorial: https://github.com/sykefi/Habitat_monitoring_HLS 
Any improvements and suggestions also here are most welcome!
BTW: I was just wondering, why did you remove the cloud masking from your tutorial? I find it quite important.

**Comment by amfriesz** [comment]
Hey @pjhurska, we identified an issue with the quality filtering in the original tutorial. We have added the updated quality filtering back to the [HLS tutorial](https://github.com/nasa/HLS-Data-Resources/blob/main/python/tutorials/HLS_Tutorial.ipynb).
