### ISSUE TITLE
Can we query by tile?

### ISSUE THREAD

**Issue by paugalles** [nasa/HLS-Data-Resources#19]
It will be very useful to be able to query also by tile.
My guess is that it should be added in the params dictionary here:
https://github.com/nasa/HLS-Data-Resources/blob/main/python/scripts/HLS_SuPER/HLS_Su.py#L39

Is there any documentation on the API for which params can be queried?

**Comment by amfriesz** [comment]
@paugalles, the HLS_SuPER script does not have the ability to query by tile. However, there is a [bash script](https://github.com/nasa/HLS-Data-Resources/tree/main/bash/hls-bulk-download) that does query by tiles.

**Comment by amfriesz** [comment]
Closing issue. Will open again if user comments.
