### ISSUE TITLE
HLS script issue about the search_response

### ISSUE THREAD

**Issue by quelladai** [nasa/HLS-Data-Resources#23]
Hello, when running the hls_subset function in HLS_Su.py, the numberReturned value in the search_response does not exist. Could this be due to a change in the API response structure? The error code is: KeyError: 'numberReturned'. Is there another field name that represents the number of returned records?

**Comment by amfriesz** [comment]
@quelladai, are you still having an issue with this? We recently pushed out and update to the HLS_SuPER script.

**Comment by amfriesz** [comment]
Closing issue. Will reopen if user responds
